import "./globals.css";


export const metadata = {
  title: "Api Using And Routing",
  description: "Generated by Api Using And Routing",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>{children}</body>
    </html>
  );
}
